import { COMETCHAT_API_VERSION, COMETCHAT_APP_ID, COMETCHAT_AUTH_KEY, COMETCHAT_REGION, COMETCHAT_REST_API_KEY } from "../../constants/EnvConstants";

//Client-Side APP CONSTANTS
export const COMETCHAT_CONSTANTS = {
    APP_ID: COMETCHAT_APP_ID,
    REGION: COMETCHAT_REGION,
    AUTH_KEY: COMETCHAT_AUTH_KEY,
    REST_API_KEY: COMETCHAT_REST_API_KEY,
    COMET_CHAT_API_VERSION: COMETCHAT_API_VERSION,
};
